services:
    dataTable.factory:
        class: Rubius\DataTablesBundle\Factory\DataTablesFactory
    abstract.dataTable.strategy:
        public: false
        abstract: true
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@templating"
            - "@translator"
            - "@request_stack"
#    Example
#    users.strategy:
#          class: Rubius\ClassNameSpace
#          parent: abstract.dataTable.strategy
#          tags:
#            - { name: dataTable.strategy, alias: users }