services:
    datagrid.factory:
        class: SliceBundle\Grid\GridFactoryNew

    abstract.datagrid.strategy:
        public: false
        abstract: true
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@templating"
            - "@translator"
            - "@request_stack"